### What is Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

https://pandas.pydata.org/about/index.html

### Pandas Series

A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

### Importing Pandas

In [1]:
import numpy as np
import pandas as pd

In [7]:
country = ["Pakistan", "Palestine", "Saudi Arabia", "Qatar","UAE" ]
pd.Series(country)

0        Pakistan
1       Palestine
2    Saudi Arabia
3           Qatar
4             UAE
dtype: object

In [9]:
# custom index
marks = [75, 59, 80, 87]
subjects = ['History', 'Science', 'Maths', 'Urdu']

pd.Series(marks, index=subjects)

History    75
Science    59
Maths      80
Urdu       87
dtype: int64

In [10]:
pd.Series(marks, index=subjects, name='marks of Ali')

History    75
Science    59
Maths      80
Urdu       87
Name: marks of Ali, dtype: int64

### Series from dict

In [14]:
marks = {
    'History':    75,
    'Science':    59,
    'Maths':      80,
    'Urdu':       87,
}

marks_series = pd.Series(marks, name="Ali ke marks")
marks_series

History    75
Science    59
Maths      80
Urdu       87
Name: Ali ke marks, dtype: int64

### Series Attributes

In [16]:
# size
marks_series.size

4

In [17]:
# dtype
marks_series.dtype

dtype('int64')

In [18]:
# name
marks_series.name

'Ali ke marks'

In [22]:
# is_unique
marks_series.is_unique

True

In [29]:
# index
marks_series.index

Index(['History', 'Science', 'Maths', 'Urdu'], dtype='object')

In [ ]:
# values
marks_series.values

array([75, 59, 80, 87], dtype=int64)

### Series using read_csv

In [43]:
# with one col
subs = pd.read_csv('./DataSet/subs.csv').squeeze()
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [3]:
vk = pd.read_csv('./DataSet/kohli_ipl.csv', index_col='match_no').squeeze()
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [4]:
moveis = pd.read_csv('./DataSet/bollywood.csv', index_col='movie').squeeze()
moveis

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

### Series methods

In [ ]:
# head
subs.head(20)

0     48
1     57
2     40
3     43
4     44
5     46
6     33
7     40
8     44
9     74
10    49
11    56
12    49
13    42
14    39
15    44
16    54
17    51
18    40
19    37
Name: Subscribers gained, dtype: int64

In [ ]:
# tail
subs.tail(10)

355    149
356    156
357    177
358    210
359    209
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, dtype: int64

In [48]:
# sample
moveis.sample(7)

movie
Hotel Salvation              Adil Hussain
Aisa Kyon Hota Hai?        Rati Agnihotri
Yeh Khula Aasmaan              Anya Anand
Mirch                      Arunoday Singh
Guru (2007 film)       Mithun Chakraborty
Direct Ishq              Rajniesh Duggall
Anamika (2008 film)            Dino Morea
Name: lead, dtype: object

In [72]:
# value_counts
moveis.value_counts()

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Diganth              1
Parveen Kaur         1
Seema Azmi           1
Akanksha Puri        1
Edwin Fernandes      1
Name: count, Length: 566, dtype: int64

In [ ]:
# sort_values
moveis.sort_values(ascending=False).head().values[0]

'Zeenat Aman'

In [81]:
# sort_index
moveis.sort_index()

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: object

### Series Maths Methods

In [39]:
# count
vk.count()

215

In [ ]:
# sum -> product
subs.sum()
# subs.product()

0

In [58]:
# mean -> median -> mode -> std -> var
subs.mean()
print(vk.median())
print(moveis.mode())
print(subs.std())
print(vk.var())

24.0
0    Akshay Kumar
Name: lead, dtype: object
62.6750230372527
688.0024777222343

In [62]:
# min/max
subs.min()
subs.max()

396

In [64]:
subs.describe()

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

### Series Indexing

In [80]:
x = pd.Series([12,13,14,35,46,57,58,79,9])
x[-3:]

6    58
7    79
8     9
dtype: int64

In [77]:
moveis[-8]

C:\Users\abdul\AppData\Local\Temp\ipykernel_12148\2784431060.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  moveis[-8]

'Arshad Warsi'

In [ ]:
# fancy indexing
vk[[1,2,3,4]]

match_no
1     1
2    23
3    13
4    12
Name: runs, dtype: int64

In [83]:
# indexing with labels -> fancy indexing
moveis['2 States (2014 film)']

'Arjun Kapoor'

### Creating DataFrame

In [ ]:
# using list

student_data = [
    [100, 80, 10],
    [190, 70, 20],
    [120, 90, 10],
]


pd.DataFrame(student_data, columns=['iq', 'marks', 'packages'])

    iq  marks  packages
0  100     80        10
1  190     70        20
2  120     90        10

In [3]:
# using dictionary
student_data = {
    'name': ['ali', 'saad', 'asif'],
    'iq': [100, 20, 30],
    'marks': [90, 70, 71],
    'pay':[120, 90, 89]
}

students= pd.DataFrame(student_data)
students.set_index('name', inplace=True)
students

       iq  marks  pay
name
ali   100     90  120
saad   20     70   90
asif   30     71   89

In [2]:
# using read_csv
moveis = pd.read_csv('./DataSet/movies.csv')
moveis

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [8]:
ipl = pd.read_csv('./DataSet/ipl-matches.csv')
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

### DataFrame Attributes and Methods

In [17]:
# shape
ipl.shape

(950, 20)

In [16]:
# dtypes
ipl.dtypes

ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [15]:
# index
ipl.index

RangeIndex(start=0, stop=950, step=1)

In [18]:
# columns
ipl.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')

In [27]:
# values 
ipl.values

array([[1312200, 'Ahmedabad', '2022-05-29', ...,
        "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312199, 'Ahmedabad', '2022-05-27', ...,
        "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312198, 'Kolkata', '2022-05-25', ...,
        "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']",
        'J Madanagopal', 'MA Gough'],
       ...,
       [335984, 'Delhi', '2008-04-19', ...,
        "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']",
        'Aleem Dar', 'GA Pratapkumar'],
       [335983, 'Chandigarh', '2008-04-19', ...,
        "['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'P Amarnath', 'MS Gony', 'M Muralitharan']",
        'MR Benson', 'SL Shastri'],
       [335982, 'Bangalore', '2008-04-18', ...,
        "['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma']",
        'Asad Rauf', 'RE Koertzen']], dtype=object)

In [33]:
# head & tail
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [5]:
ipl.tail(8)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
942,335989,Chennai,2008-04-23,2007/08,8,Chennai Super Kings,Mumbai Indians,"MA Chidambaram Stadium, Chepauk",Mumbai Indians,field,N,Chennai Super Kings,Runs,6.0,NaN,ML Hayden,"['PA Patel', 'ML Hayden', 'MEK Hussey', 'SK Ra...","['L Ronchi', 'ST Jayasuriya', 'RV Uthappa', 'S...",DJ Harper,GA Pratapkumar
943,335988,Hyderabad,2008-04-22,2007/08,7,Deccan Chargers,Delhi Daredevils,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,bat,N,Delhi Daredevils,Wickets,9.0,NaN,V Sehwag,"['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...","['G Gambhir', 'V Sehwag', 'S Dhawan', 'Shoaib ...",IL Howell,AM Saheba
944,335987,Jaipur,2008-04-21,2007/08,6,Rajasthan Royals,Kings XI Punjab,Sawai Mansingh Stadium,Kings XI Punjab,bat,N,Rajasthan Royals,Wickets,6.0,NaN,SR Watson,"['M Kaif', 'Kamran Akmal', 'YK Pathan', 'SR Wa...","['K Goel', 'JR Hopes', 'KC Sangakkara', 'DPMD ...",Aleem Dar,RB Tiffin
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [35]:
# sample
ipl.sample(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
902,336032,Delhi,2008-05-24,2007/08,50,Delhi Daredevils,Mumbai Indians,Feroz Shah Kotla,Delhi Daredevils,field,N,Delhi Daredevils,Wickets,5.0,NaN,KD Karthik,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['ST Jayasuriya', 'SR Tendulkar', 'DR Smith', ...",BF Bowden,K Hariharan
208,1178421,Delhi,2019-04-28,2019,46,Delhi Capitals,Royal Challengers Bangalore,Arun Jaitley Stadium,Delhi Capitals,bat,N,Delhi Capitals,Runs,16.0,NaN,S Dhawan,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['PA Patel', 'V Kohli', 'AB de Villiers', 'S D...",BNJ Oxenford,KN Ananthapadmanabhan
361,1082602,Bangalore,2017-04-14,2017,12,Royal Challengers Bangalore,Mumbai Indians,M Chinnaswamy Stadium,Mumbai Indians,field,N,Mumbai Indians,Wickets,4.0,NaN,KA Pollard,"['CH Gayle', 'V Kohli', 'AB de Villiers', 'KM ...","['PA Patel', 'JC Buttler', 'RG Sharma', 'MJ Mc...",KN Ananthapadmanabhan,AK Chaudhary
891,392181,Cape Town,2009-04-18,2009,1,Chennai Super Kings,Mumbai Indians,Newlands,Chennai Super Kings,field,N,Mumbai Indians,Runs,19.0,NaN,SR Tendulkar,"['PA Patel', 'ML Hayden', 'SK Raina', 'A Flint...","['ST Jayasuriya', 'SR Tendulkar', 'S Dhawan', ...",BR Doctrove,K Hariharan
190,1216496,NaN,2020-09-22,2020/21,4,Rajasthan Royals,Chennai Super Kings,Sharjah Cricket Stadium,Chennai Super Kings,field,N,Rajasthan Royals,Runs,16.0,NaN,SV Samson,"['YBK Jaiswal', 'SPD Smith', 'SV Samson', 'DA ...","['M Vijay', 'SR Watson', 'F du Plessis', 'SM C...",C Shamshuddin,VA Kulkarni

In [37]:
# info
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [40]:
# describe
ipl.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [10]:
# isnull
ipl.isnull().sum()

ID                   0
City                51
Date                 0
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

In [11]:
# duplicated
moveis.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1624    False
1625    False
1626    False
1627    False
1628    False
Length: 1629, dtype: bool

In [21]:
# rename
students
students.rename(columns={'marks':'percent','lpa':'package'})
students

    iq  marks  packages
0  100     80        10
1  190     70        20
2  120     90        10

In [19]:
students

    iq  marks  packages
0  100     80        10
1  190     70        20
2  120     90        10

### Math Methods

In [31]:
# sum -> axis argument
students.sum(axis=0)

iq          410
marks       240
packages     40
dtype: int64

In [32]:
students.var()

iq          2233.333333
marks        100.000000
packages      33.333333
dtype: float64

### Selecting cols from a DataFrame

In [34]:
# single cols
ipl["City"]

0       Ahmedabad
1       Ahmedabad
2         Kolkata
3         Kolkata
4          Mumbai
          ...
945       Kolkata
946        Mumbai
947         Delhi
948    Chandigarh
949     Bangalore
Name: City, Length: 950, dtype: object

In [38]:
# multiple cols
ipl[["TossDecision","TossWinner","WinningTeam"]]

    TossDecision                   TossWinner                  WinningTeam
0            bat             Rajasthan Royals               Gujarat Titans
1          field             Rajasthan Royals             Rajasthan Royals
2          field         Lucknow Super Giants  Royal Challengers Bangalore
3          field               Gujarat Titans               Gujarat Titans
4            bat          Sunrisers Hyderabad                 Punjab Kings
..           ...                          ...                          ...
945          bat              Deccan Chargers        Kolkata Knight Riders
946          bat               Mumbai Indians  Royal Challengers Bangalore
947          bat             Rajasthan Royals             Delhi Daredevils
948          bat          Chennai Super Kings          Chennai Super Kings
949        field  Royal Challengers Bangalore        Kolkata Knight Riders

[950 rows x 3 columns]

### Selecting rows from a DataFrame

*   List item
*   List item



- **iloc** - searches using index positions
- **loc** - searches using index labels

In [49]:
# single row
students.iloc[0]

iq       100
marks     90
pay      120
Name: ali, dtype: int64

In [47]:
# loc
students.loc['ali']

iq       100
marks     90
pay      120
Name: ali, dtype: int64

In [35]:
students.loc['ali':'saad']

       iq  marks  pay
name
ali   100     90  120
saad   20     70   90

### Selecting both rows and cols

In [51]:
moveis.iloc[0:3,0:3]

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

In [45]:
moveis.loc[0:2,'title_x':'poster_path']

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

### Filtering a DataFrame

In [55]:
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [59]:
# find all the final winners
mask = ipl["MatchNumber"] == "Final"
new_df = ipl[mask]
new_df[['Season', 'WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [66]:
# how many super over finishes have occured
ipl[ipl["SuperOver"] == "Y"]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
114,1254077,Chennai,2021-04-25,2021,20,Delhi Capitals,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk, Chennai",Delhi Capitals,bat,Y,Delhi Capitals,SuperOver,NaN,NaN,PP Shaw,"['PP Shaw', 'S Dhawan', 'RR Pant', 'SPD Smith'...","['DA Warner', 'JM Bairstow', 'KS Williamson', ...",CB Gaffaney,KN Ananthapadmanabhan
158,1216512,Abu Dhabi,2020-10-18,2020/21,35,Kolkata Knight Riders,Sunrisers Hyderabad,Sheikh Zayed Stadium,Sunrisers Hyderabad,field,Y,Kolkata Knight Riders,SuperOver,NaN,NaN,LH Ferguson,"['Shubman Gill', 'RA Tripathi', 'N Rana', 'AD ...","['JM Bairstow', 'KS Williamson', 'PK Garg', 'D...",PG Pathak,S Ravi
159,1216517,NaN,2020-10-18,2020/21,36,Mumbai Indians,Kings XI Punjab,Dubai International Cricket Stadium,Mumbai Indians,bat,Y,Kings XI Punjab,SuperOver,NaN,NaN,KL Rahul,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...","['KL Rahul', 'MA Agarwal', 'CH Gayle', 'N Poor...",Nitin Menon,PR Reiffel
184,1216547,NaN,2020-09-28,2020/21,10,Royal Challengers Bangalore,Mumbai Indians,Dubai International Cricket Stadium,Mumbai Indians,field,Y,Royal Challengers Bangalore,SuperOver,NaN,NaN,AB de Villiers,"['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",Nitin Menon,PR Reiffel
192,1216493,NaN,2020-09-20,2020/21,2,Delhi Capitals,Kings XI Punjab,Dubai International Cricket Stadium,Kings XI Punjab,field,Y,Delhi Capitals,SuperOver,NaN,NaN,MP Stoinis,"['PP Shaw', 'S Dhawan', 'SO Hetmyer', 'SS Iyer...","['KL Rahul', 'MA Agarwal', 'KK Nair', 'N Poora...",AK Chaudhary,Nitin Menon
203,1178426,Mumbai,2019-05-02,2019,51,Mumbai Indians,Sunrisers Hyderabad,Wankhede Stadium,Mumbai Indians,bat,Y,Mumbai Indians,SuperOver,NaN,NaN,JJ Bumrah,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'E Lewi...","['WP Saha', 'MJ Guptill', 'MK Pandey', 'KS Wil...",CK Nandan,S Ravi
244,1175365,Delhi,2019-03-30,2019,10,Kolkata Knight Riders,Delhi Capitals,Arun Jaitley Stadium,Delhi Capitals,field,Y,Delhi Capitals,SuperOver,NaN,NaN,PP Shaw,"['NS Naik', 'CA Lynn', 'RV Uthappa', 'N Rana',...","['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...",AY Dandekar,Nitin Menon
339,1082625,Rajkot,2017-04-29,2017,35,Gujarat Lions,Mumbai Indians,Saurashtra Cricket Association Stadium,Gujarat Lions,bat,Y,Mumbai Indians,SuperOver,NaN,NaN,KH Pandya,"['Ishan Kishan', 'BB McCullum', 'SK Raina', 'A...","['PA Patel', 'JC Buttler', 'N Rana', 'RG Sharm...",AK Chaudhary,CB Gaffaney
474,829741,Ahmedabad,2015-04-21,2015,18,Rajasthan Royals,Kings XI Punjab,"Sardar Patel Stadium, Motera",Kings XI Punjab,field,Y,Kings XI Punjab,SuperOver,NaN,NaN,SE Marsh,"['AM Rahane', 'SR Watson', 'DJ Hooda', 'SPD Sm...","['M Vijay', 'V Sehwag', 'SE Marsh', 'GJ Maxwel...",M Erasmus,S Ravi
533,729315,Abu Dhabi,2014-04-29,2014,19,Kolkata Knight Riders,Rajasthan Royals,Sheikh Zayed Stadium,Rajasthan Royals,bat,Y,Rajasthan Royals,SuperOver,NaN,NaN,JP Faulkner,"['G Gambhir', 'MS Bisla', 'JH Kallis', 'MK Pan...","['AM Rahane', 'KK Nair', 'SV Samson', 'SR Wats...",Aleem Dar,AK Chaudhary
608,598017,Bangalore,2013-04-16,2013,21,Royal Challengers Bangalore,Delhi Daredevils,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Y,Royal Challengers Bangalore,SuperOver,NaN,NaN,V Kohli,"['CH Gayle', 'KL Rahul', 'V Kohli', 'AB de Vil...","['DA Warner', 'V Sehwag', 'MC Juneja', 'DPMD J...",M Erasmus,VA Kulkarni
621,598004,Hyderabad,2013-04-07,2013,7,Sunrisers Hyderabad,Royal Challengers Bangalore,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore,bat,Y,Sunrisers Hyderabad,SuperOver,NaN,NaN,GH Vihari,"['PA Reddy', 'PA Patel', 'CL White', 'GH Vihar...","['CH Gayle', 'TM Dilshan', 'V Kohli', 'KK Nair...",AK Chaudhary,S Ravi
819,419121,Chennai,2010-03-21,2009/10,16,Chennai Super Kings,Kings XI Punjab,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,field,Y,Kings XI Punjab,SuperOver,NaN,NaN,J Theron,"['PA Patel', 'ML Hayden', 'SK Raina', 'M Vijay...","['RS Bopara', 'IK Pathan', 'KC Sangakkara', 'D...",K Hariharan,DJ Harper
883,392190,Cape Town,2009-04-23,2009,10,Kolkata Knight Riders,Rajasthan Royals,Newlands,Kolkata Knight Riders,field,Y,Rajasthan Royals,SuperOver,NaN,NaN,YK Pathan,"['CH Gayle', 'BB McCullum', 'LR Shukla', 'BJ H...","['GC Smith', 'PC Valthaty', 'RJ Quiney', 'YK P...",MR Benson,M Erasmus

In [68]:
ipl.head(3)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough

In [78]:
# how many matches has csk won in kolkata
ipl[(ipl['City'] == "Kolkata") & (ipl["WinningTeam"] == "Chennai Super Kings")].shape[0]

5

In [89]:
# The team that wins the coin toss often wins the game. 
ipl[ipl["TossWinner"] == ipl["WinningTeam"]].shape[0]/ipl.shape[0]*100

51.473684210526315

In [97]:
# movies with rating higher than 8 and votes>10000
moveis[(moveis["imdb_rating"] > 8) & (moveis["imdb_votes"] > 10000)].shape[0]

43

In [110]:
# Action movies with rating higher than 7.5

mask_1 = moveis["genres"].str.contains("Action")
mask_2 = moveis["imdb_rating"] > 7.5


moveis[mask_1 & mask_2]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
41,Family of Thakurganj,tt8897986,https://upload.wikimedia.org/wikipedia/en/9/99...,https://en.wikipedia.org/wiki/Family_of_Thakur...,Family of Thakurganj,Family of Thakurganj,0,2019,127,Action|Drama,9.4,895,The film is based on small town of North India...,The film is based on small town of North India...,NaN,Jimmy Sheirgill|Mahie Gill|Nandish Singh|Prana...,NaN,19 July 2019 (India)
84,Mukkabaaz,tt7180544,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mukkabaaz,The Brawler,Mukkabaaz,0,2017,154,Action|Drama|Sport,8.1,5434,A boxer (Shravan) belonging to upper cast tra...,A boxer struggles to make his mark in the boxi...,NaN,Viineet Kumar|Jimmy Sheirgill|Zoya Hussain|Rav...,3 wins & 6 nominations,12 January 2018 (USA)
106,Raazi,tt7098658,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raazi,Raazi,Raazi,0,2018,138,Action|Drama|Thriller,7.8,20289,Hidayat Khan is the son of an Indian freedom f...,A Kashmiri woman agrees to marry a Pakistani a...,An incredible true story,Alia Bhatt|Vicky Kaushal|Rajit Kapoor|Shishir ...,21 wins & 26 nominations,11 May 2018 (USA)
110,Parmanu: The Story of Pokhran,tt6826438,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Parmanu:_The_Sto...,Parmanu: The Story of Pokhran,Parmanu: The Story of Pokhran,0,2018,129,Action|Drama|History,7.7,18292,Captain Ashwat Raina's efforts to turn India i...,Ashwat Raina and his teammates arrive in Pokhr...,1998| India: one secret operation| six Indians...,John Abraham|Boman Irani|Diana Penty|Anuja Sat...,NaN,25 May 2018 (USA)
112,Bhavesh Joshi Superhero,tt6129302,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bhavesh_Joshi_Su...,Bhavesh Joshi Superhero,Bhavesh Joshi Superhero,0,2018,154,Action|Drama,7.6,4928,Bhavesh Joshi Superhero is an action film abou...,The origin story of Bhavesh Joshi an Indian s...,This year| justice will have a new name.,Harshvardhan Kapoor|Priyanshu Painyuli|Ashish ...,2 nominations,1 June 2018 (USA)
169,The Ghazi Attack,tt6299040,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Ghazi_Attack...,The Ghazi Attack,The Ghazi Attack,0,2017,116,Action|Thriller|War,7.6,10332,In 1971 amid rising tensions between India an...,A Pakistani submarine Ghazi plans to secretly...,The war you did not know about,Rana Daggubati|Kay Kay Menon|Atul Kulkarni|Om ...,1 win & 7 nominations,17 February 2017 (USA)
219,Raag Desh (film),tt6080746,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raagdesh,Raag Desh,Raag Desh,0,2017,135,Action|Drama|History,8.3,341,A period film based on the historic 1945 India...,A period film based on the historic 1945 India...,NaN,Kunal Kapoor|Amit Sadh|Mohit Marwah|Kenneth De...,NaN,28 July 2017 (India)
258,Irudhi Suttru,tt5310090,https://upload.wikimedia.org/wikipedia/en/f/fe...,https://en.wikipedia.org/wiki/Saala_Khadoos,Saala Khadoos,Saala Khadoos,0,2016,109,Action|Drama|Sport,7.6,10507,An under-fire boxing coach Prabhu is transfer...,The story of a former boxer who quits boxing f...,NaN,Madhavan|Ritika Singh|Mumtaz Sorcar|Nassar|Rad...,9 wins & 2 nominations,29 January 2016 (USA)
280,Laal Rang,tt5600714,NaN,https://en.wikipedia.org/wiki/Laal_Rang,Laal Rang,Laal Rang,0,2016,147,Action|Crime|Drama,8.0,3741,The friendship of two men is tested when thing...,The friendship of two men is tested when thing...,Every job good or bad| must be done with honesty.,Randeep Hooda|Akshay Oberoi|Rajniesh Duggall|P...,NaN,22 April 2016 (India)
297,Udta Punjab,tt4434004,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Udta_Punjab,Udta Punjab,Udta Punjab,0,2016,148,Action|Crime|Drama,7.8,23995,What on earth can a rock star a migrant labor...,A story that revolves around drug abuse in the...,NaN,Shahid Kapoor|Alia Bhatt|Kareena Kapoor|Diljit...,11 wins & 19 nominations,17 June 2016 (USA)
354,Dangal (film),tt5074352,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dangal_(film),Dangal,Dangal,0,2016,161,Action|Biography|Drama,8.4,131338,Biopic of Mahavir Singh Phogat who taught wre...,Former wrestler Mahavir Singh Phogat and his t...,You think our girls are any lesser than boys?,Aamir Khan|Fatima Sana Shaikh|Sanya Malhotra|S...,23 wins & 4 nominations,21 December 2016 (USA)
362,Bajrangi Bhaijaan,tt3863552,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bajrangi_Bhaijaan,Bajrangi Bhaijaan,Bajrangi Bhaijaan,0,2015,163,Action|Comedy|Drama,8.0,65877,A little mute girl from a Pakistani village ge...,An Indian man with a magnanimous heart takes a...,NaN,Salman Khan|Harshaali Malhotra|Nawazuddin Sidd...,25 wins & 13 nominations,17 July 2015 (USA)
365,Baby (2015 Hindi film),tt3848892,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Baby_(2015_Hindi...,Baby,Baby,0,2015,159,Action|Thriller,8.0,49426,The country is perpetually under threat from t...,An elite counter-intelligence unit learns of a...,History Is Made By Those Who Give A Damn!,Akshay Kumar|Danny Denzongpa|Rana Daggubati|Ta...,1 win,23 January 2015 (India)
393,Detective Byomkesh Bakshy!,tt3447364,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Detective_Byomke...,Detective Byomkesh Bakshy!,Detective Byomkesh Bakshy!,0,2015,139,Action|Mystery|Thriller,7.6,14674,CALCUTTA 1943 A WAR - A MYSTERY - and A DETECT...,While investigating the disappearance of a che...,Expect The Unexpected,Sushant Singh Rajput|Anand Tiwari|Neeraj Kabi|...,NaN,3 April 2015 (USA)
449,Titli (2014 film),tt3019620,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Titli_(2014_film),Titli,Titli,0,2014,116,Action|Drama|Thriller,7.6,3677,In the badlands of Delhi's dystopic underbelly...,A Hindi feature film set in the lower depths o...,Daring| Desireable| Dangerous,Nawazuddin Siddiqui|Niharika Singh|Anil George...,4 wins & 5 nominations,20 June 2014 (USA)
536,Haider (film),tt3390572,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Haider_(film),Haider,Haider,0,2014,160,Action|Crime|Drama,8.1,46912,Vishal Bhardwaj's adaptation of William Shakes...,A young man returns to Kashmir after his fathe...,NaN,Tabu|Shahid Kapoor|Shraddha Kapoor|Kay Kay Men...,28 wins & 24 nominations,2 October 2014 (USA)
589,Vishwaroopam,tt2199711,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Vishwaroop_(Hind...,Vishwaroopam,Vishwaroopam,0,2013,148,Action|Thriller,8.2,38016,Vishwanathan a Kathak dance teacher in New Yo...,When a classical dancer's suspecting wife sets...,NaN,Kamal Haasan|Rahul Bose|Shekhar Kapur|Pooja Ku...,5 wins & 11 nominations,25 January 2013 (India)
625,Madras Cafe,tt2855648,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Madras_Cafe,Madras Cafe,Madras Cafe,0,2013,130,Action|Drama|Thriller,7.7,21393,An Indian Intelligence agent (portrayed by Joh...,An Indian intelligence agent journeys to a war...,NaN,John Abraham|Nargis Fakhri|Raashi Khanna|Praka...,10 wins & 10 nominations,23 August 2013 (India)
668,Paan Singh Tomar (film),tt1620933,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Paan_Singh_Tomar...,Paan Singh Tomar,Paan Singh Tomar,0,2012,135,Action|Biography|Crime,8.2,29994,Paan Singh Tomar is a Hindi-language film bas...,The story of Paan Singh Tomar an Indian athle...,NaN,Irrfan Khan|,10 wins & 11 nominations,2 March 2012 (USA)
693,Gangs of Wasseypur,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseypur,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
694,Gangs of Wasseypur – Part 2,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseyp...,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
982,Jodhaa Akbar,tt0449994,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Jodhaa_Akbar,Jodhaa Akbar,Jodhaa Akbar,0,2008,213,Action|Drama|History,7.6,27541,Jodhaa Akbar is a sixteenth century love story...,A sixteenth century love story about a marriag...,NaN,Hrithik Roshan|Aishwarya Rai Bachchan|Sonu Soo...,32 wins & 21 nominations,15 February 2008 (USA)
1039,1971 (2007 film),tt0983990,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/1971_(2007_film),1971,1971,0,2007,160,Action|Drama|War,7.9,1121,Based on true facts the film revolves around ...,Based on true facts the film revolves around ...,Honor the heroes.......,Manoj Bajpayee|Ravi Kishan|Deepak Dobriyal|,1 win,9 March 2007 (India)
1058,Black Friday (2007 film),tt0400234,https://upload.wikimedia.org/wikipedia/en/5/58...,https://en.wikipedia.org/wiki/Black_Friday_(20...,Black Friday,Black Friday,0,2004,143,Action|Crime|Drama,8.5,16761,A dramatic presentation of the bomb blasts tha...,Black Friday is a film about the investigation...,The story of the Bombay bomb blasts,Kay Kay Menon|Pavan Malhotra|Aditya Srivastava...,3 nominations,9 February 2007 (India)
1188,Omkara (2006 film),tt0488414,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Omkara_(2006_film),Omkara,Omkara,0,2006,155,Action|Crime|Drama,8.1,17594,Advocate Raghunath Mishra has arranged the mar...,A politically-minded enforcer's misguided trus...,NaN,Ajay Devgn|Saif Ali Khan|Vivek Oberoi|Kareena ...,19 wins & 20 nominations,28 July 2006 (USA)
1293,Sarkar (2005 film),tt0432047,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sarkar_(2005_film),Sarkar,Sarkar,0,2005,124,Action|Crime|Drama,7.6,14694,Meet Subhash Nagre - a wealthy and influential...,The authority of a man who runs a parallel go...,'There are no Rights and Wrongs. Only Power' -...,Amitabh Bachchan|Abhishek Bachchan|Kay Kay Men...,2 wins & 10 nominations,1 July 2005 (India)
1294,Sehar,tt0477857,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sehar,Sehar,Sehar,0,2005,125,Action|Crime|Drama,7.8,1861,At the tender age of 8 Ajay Kumar is traumatiz...,Ajay Kumar the newly appointed honest SSP of ...,NaN,Arshad Warsi|Pankaj Kapur|Mahima Chaudhry|Sush...,NaN,29 July 2005 (India)
1361,Lakshya (film),tt0323013,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lakshya_(film),Lakshya,Lakshya,0,2004,186,Action|Drama|Romance,7.9,18777,Karan is a lazy good-for-nothing who lives on ...,An aimless jobless irresponsible grown man j...,It took him 24 years and 18000 feet to find hi...,Hrithik Roshan|Preity Zinta|Amitabh Bachchan|O...,4 wins & 10 nominations,18 June 2004 (USA)
1432,Gangaajal,tt0373856,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangaajal,Gangaajal,Gangaajal,0,2003,157,Action|Crime|Drama,7.8,14295,An SP Amit Kumar who is given charge of Tezpur...,An IPS officer motivates and leads a dysfuncti...,NaN,Ajay Devgn|Gracy Singh|Mohan Joshi|Yashpal Sha...,4 wins & 29 nominations,29 August 2003 (India)
1495,Company (film),tt0296574,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Company_(film),Company,Company,0,2002,155,Action|Crime|Drama,8.0,13474,Mallik is a henchman of Aslam Bhai a Mumbai u...,A small-time gangster named Chandu teams up wi...,A law & order enterprise,Ajay Devgn|Mohanlal|Manisha Koirala|Seema Bisw...,16 wins & 9 nominations,15 April 2002 (India)
1554,The Legend of Bhagat Singh,tt0319736,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Legend_of_Bh...,The Legend of Bhagat Singh,The Legend of Bhagat Singh,0,2002,155,Action|Biography|Drama,8.1,13455,Bhagat was born in British India during the ye...,The story of a young revolutionary who raised ...,NaN,Ajay Devgn|Sushant Singh|D. Santosh|Akhilendra...,11 wins & 5 nominations,7 June 2002 (India)
1607,Nayak (2001 Hindi film),tt0291376,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Nayak_(2001_Hind...,Nayak: The Real Hero,Nayak: The Real Hero,0,2001,187,Action|Drama|Thriller,7.8,12522,Employed as a camera-man at a popular televisi...,A man accepts a challenge by the chief ministe...,Fight the power,Anil Kapoor|Rani Mukerji|Amrish Puri|Johnny Le...,2 nominations,7 September 2001 (India)

### Adding new cols

In [8]:
# completely new
moveis['Country'] = "Indai"
moveis

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),Indai
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),Indai
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA),Indai
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA),Indai
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India),Indai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India),Indai
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India),Indai
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN,Indai
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA),Indai
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012),Indai